/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grimoire.image_viewing.views;

import grimoire.Grimoire;

/**
 *
 * @author arthur
 */
public class SettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        thresholdSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        gaussianBlurSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        birhgtnessSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        motionDetectionSlider = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        motionSizeSlider = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        bufferSizeSlider = new javax.swing.JSlider();

        jLabel1.setText("Threshold");

        thresholdSlider.setMajorTickSpacing(100000);
        thresholdSlider.setMaximum(255000);
        thresholdSlider.setMinorTickSpacing(10000);
        thresholdSlider.setPaintTicks(true);
        thresholdSlider.setValue(25000);
        thresholdSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thresholdSliderStateChanged(evt);
            }
        });

        jLabel2.setText("Gaussian Blur");

        gaussianBlurSlider.setMajorTickSpacing(4);
        gaussianBlurSlider.setMaximum(35);
        gaussianBlurSlider.setMinimum(1);
        gaussianBlurSlider.setMinorTickSpacing(2);
        gaussianBlurSlider.setPaintTicks(true);
        gaussianBlurSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gaussianBlurSliderStateChanged(evt);
            }
        });

        jLabel3.setText("Brightness Threshold");

        birhgtnessSlider.setMajorTickSpacing(100);
        birhgtnessSlider.setMaximum(1000);
        birhgtnessSlider.setMinorTickSpacing(50);
        birhgtnessSlider.setPaintTicks(true);
        birhgtnessSlider.setValue(600);
        birhgtnessSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                birhgtnessSliderStateChanged(evt);
            }
        });

        jLabel4.setText("Motion Detection Distance");

        motionDetectionSlider.setMajorTickSpacing(10);
        motionDetectionSlider.setMinorTickSpacing(5);
        motionDetectionSlider.setPaintTicks(true);
        motionDetectionSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                motionDetectionSliderStateChanged(evt);
            }
        });

        jLabel5.setText("Motion Size Limit");

        motionSizeSlider.setMajorTickSpacing(10);
        motionSizeSlider.setMinorTickSpacing(5);
        motionSizeSlider.setPaintTicks(true);
        motionSizeSlider.setToolTipText("");
        motionSizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                motionSizeSliderStateChanged(evt);
            }
        });

        jLabel6.setText("Buffer Size");

        bufferSizeSlider.setMajorTickSpacing(50);
        bufferSizeSlider.setMaximum(300);
        bufferSizeSlider.setMinimum(1);
        bufferSizeSlider.setMinorTickSpacing(10);
        bufferSizeSlider.setPaintTicks(true);
        bufferSizeSlider.setValue(150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thresholdSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gaussianBlurSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(birhgtnessSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(motionSizeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(motionDetectionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addComponent(bufferSizeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gaussianBlurSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(birhgtnessSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motionDetectionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motionSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bufferSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void thresholdSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thresholdSliderStateChanged
        // TODO add your handling code here:
        double newVal = this.thresholdSlider.getValue() / 1000.0;
        Grimoire.UserSettings.MOTION_THRESHOLD = newVal;
    }//GEN-LAST:event_thresholdSliderStateChanged

    private void gaussianBlurSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gaussianBlurSliderStateChanged
        // TODO add your handling code here:
        int newVal = this.gaussianBlurSlider.getValue();
        if(newVal % 2 ==0)
        newVal += 1;
        this.gaussianBlurSlider.setValue(newVal);
        Grimoire.UserSettings.GAUSSIAN_KERNEL_SIZE = newVal;
    }//GEN-LAST:event_gaussianBlurSliderStateChanged

    private void birhgtnessSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_birhgtnessSliderStateChanged
        // TODO add your handling code here:
        double newVal = this.birhgtnessSlider.getValue() / 1000.0;
        Grimoire.UserSettings.INTENSITY_THRESHOLD = newVal;
    }//GEN-LAST:event_birhgtnessSliderStateChanged

    private void motionDetectionSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_motionDetectionSliderStateChanged
        // TODO add your handling code here:
        Grimoire.UserSettings.MOTION_DETECTION_DISTANCE = this.motionDetectionSlider.getValue();
    }//GEN-LAST:event_motionDetectionSliderStateChanged

    private void motionSizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_motionSizeSliderStateChanged
        // TODO add your handling code here:
        Grimoire.UserSettings.MAX_MOTION_SIZE_LIMIT = this.motionSizeSlider.getValue();
    }//GEN-LAST:event_motionSizeSliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider birhgtnessSlider;
    private javax.swing.JSlider bufferSizeSlider;
    private javax.swing.JSlider gaussianBlurSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSlider motionDetectionSlider;
    private javax.swing.JSlider motionSizeSlider;
    private javax.swing.JSlider thresholdSlider;
    // End of variables declaration//GEN-END:variables
}
